### ISSUE TITLE
unusable in darkmode 

### ISSUE THREAD

**Issue by sn55997** [tdulcet/Thunderbird-Send#12] opened 2024-04-28 18:37 UTC
Cant read the add-on window in thunderbird's darkmode
![image](https://github.com/tdulcet/Thunderbird-Send/assets/168368762/97187111-0d01-4e4f-8ac2-d1cf379a3c71)

**Comment by tdulcet** [comment] 2024-04-28 19:16
Thanks for the bug report. The regular dark mode works for me:
![image](https://github.com/tdulcet/Thunderbird-Send/assets/15305150/f95a163a-2509-4b0b-85f2-6c8427b90ea4)

I believe the issue is that you also enabled the high contrast mode, which is not yet supported by the library this add-on uses for the CSS. See https://github.com/TinyWebEx/AutomaticSettings/issues/23 for more information.

**Comment by sn55997** [comment] 2024-04-28 20:07
Sorry for the double post and thanks for the quick reply.

High contrast mode is not enabled! BUT: I changed the colours in Preferences>Fonts&Colours as this is the only way to get the message preview window to work in dark mode. This should not affect the options window of any add-on, but it does in some add-ons (e.g. ReplyWithHeader). If the colour preferences are set to default, dark mode works as expected in the FileLink provider for Send. But I do not want the light message preview. (Changing the forced-colours and prefers-contrast tags did not work.) So it does not seem to be caused by your code, but the "FileLink provider for box" e.g. does not have this problem in the Preferences>Compose>Attachments window. Any ideas?

 ![image](https://github.com/tdulcet/Thunderbird-Send/assets/168368762/12e854f3-20ce-404c-acf1-fd42c2914e0b) ![image](https://github.com/tdulcet/Thunderbird-Send/assets/168368762/737a71a4-eb53-437e-b7a7-563b2a966a66)
![image](https://github.com/tdulcet/Thunderbird-Send/assets/168368762/feb13da0-c9e6-4c1c-8825-e03060e8244c)

**Comment by tdulcet** [comment] 2024-04-29 10:38
Thanks for the detailed information and screenshots. My understanding is that using that override in Thunderbird has the same effect as enabling high contrast mode, so adding support for high contrast mode should resolve the issue for you. See the discussion in https://github.com/rugk/awesome-emoji-picker/issues/131, where another user had this same issue with an add-on I help maintain.

Note that Thunderbird 128 is scheduled to have support for automatically converting light message content to dark (see [bug 1715361](https://bugzilla.mozilla.org/show_bug.cgi?id=1715361)), which would allow you to have dark messages without needing to enable this override. Long term, the CSS in the library will need to be updated to support high contrast mode. I do not have the CSS knowledge to make the changes myself (which is why I use a library), so I will leave this issue open until we find a volunteer.

**Comment by sn55997** [comment] 2024-04-29 12:06
Thanks a lot, this was very helpful!

**Comment by tdulcet** [comment] 2024-09-11 10:31
This should be fixed in Thunderbird 128.

**Closed as completed by tdulcet** 2024-09-11 10:31 UTC
Labels: enhancement
